TutorGet/Models/Booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorGet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
        [DataType(DataType.DateTime)]
        [Display(Name = "Booking Time")]
        public System.DateTime BookingTime { get; set; }
        [Display(Name = "User")]
        public string UserId { get; set; }
        [Display(Name = "Tutor")]
        public int TutorId { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}

TutorGet/Controllers/BookingsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TutorGet.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace TutorGet.Controllers
{   
    public class BookingsController : Controller
    {
        private aspnetTutorGetEntities db = new aspnetTutorGetEntities();

        // GET: Bookings
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var bookLesson = db.Bookings.Where(s => s.UserId == userId).ToList();
            //var bookings = db.Bookings.Include(b => b.AspNetUser).Include(b => b.Tutor);
            return View(bookLesson);
        }


        // GET: Bookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // GET: Bookings/Create
        [Authorize]
        public ActionResult Create(int tutorid)
        {
            ViewBag.TutorId = new SelectList(db.Tutors, "Id", "Name", tutorid);                           
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,BookingTime,UserId,TutorId")] Booking booking)
        {
            booking.UserId = User.Identity.GetUserId();
            ModelState.Clear();
            TryValidateModel(booking);
            if (db.Bookings.Any(e => e.BookingTime == booking.BookingTime && e.UserId == booking.UserId))
            {
                ViewBag.TheResult = false;
            }
            else if (ModelState.IsValid)
            {
                db.Bookings.Add(booking);
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", booking.UserId);
            ViewBag.TutorId = new SelectList(db.Tutors, "Id", "Name", booking.TutorId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", booking.UserId);
            ViewBag.TutorId = new SelectList(db.Tutors, "Id", "Name", booking.TutorId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,BookingTime,UserId,TutorId")] Booking booking)
        {

            if (db.Bookings.Any(e => e.BookingTime == booking.BookingTime && e.UserId == booking.UserId))
            {
                ViewBag.TheResult = false;
            }
            else if (ModelState.IsValid)
            {
                db.Entry(booking).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.TheResult = true;
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", booking.UserId);
            ViewBag.TutorId = new SelectList(db.Tutors, "Id", "Name", booking.TutorId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Booking booking = db.Bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Booking booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private List<BlogPieChart> PopulateData()
        {
            var list = new List<BlogPieChart>();
            var userId = User.Identity.GetUserId();
            int en = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "English").Count();
            int ch = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "Chinese").Count();
            int jp = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "Japanese").Count();
            int sp = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "Spanish").Count();
            int fr = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "French").Count();
            int it = db.Bookings.Where(b => b.UserId == userId && b.Tutor.Language.LanguageName == "Italian").Count();
            if (en > 0)
            { list.Add(new BlogPieChart { Language = "English", Count = en }); }
            if (ch > 0)
            { list.Add(new BlogPieChart { Language = "Chinese", Count = ch }); }
            if (jp > 0)
            { list.Add(new BlogPieChart { Language = "Japanese", Count = jp }); }
            if (sp > 0)
            { list.Add(new BlogPieChart { Language = "Spanish", Count = sp }); }
            if (fr > 0)
            { list.Add(new BlogPieChart { Language = "French", Count = fr }); }
            if (it > 0)
            { list.Add(new BlogPieChart { Language = "Italian", Count = it }); }
            return list;
        }

        public JsonResult GetChartData()
        {
            var lessons = PopulateData();
            var chartData = new object[lessons.Count + 1];
            chartData[0] = new object[]
            {
                "Language",
                "Count"
            };
            int j = 0;
            foreach (var i in lessons)
            {
                j++;
                chartData[j] = new object[] { i.Language, i.Count };
            }
            return new JsonResult { Data = chartData, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [Authorize]
        public ActionResult Report()
        {
            return View();
        }

        private List<BlogLineChart> monthLine()
        {
            var list = new List<BlogLineChart>();
            var userId = User.Identity.GetUserId();
            int jan = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 1).Count();
            int feb = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 2).Count();
            int mar = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 3).Count();
            int apr = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 4).Count();
            int may = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 5).Count();
            int jun = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 6).Count();
            int jul = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 7).Count();
            int aug = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 8).Count();
            int sep = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 9).Count();
            int oct = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 10).Count();
            int nov = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 11).Count();
            int dec = db.Bookings.Where(b => b.UserId == userId && b.BookingTime.Month == 12).Count();
            list.Add(new BlogLineChart { Month = "01", Count = jan }); 
            list.Add(new BlogLineChart { Month = "02", Count = feb });
            list.Add(new BlogLineChart { Month = "03", Count = mar });
            list.Add(new BlogLineChart { Month = "04", Count = apr });
            list.Add(new BlogLineChart { Month = "05", Count = may });
            list.Add(new BlogLineChart { Month = "06", Count = jun });
            list.Add(new BlogLineChart { Month = "07", Count = jul });
            list.Add(new BlogLineChart { Month = "08", Count = aug });
            list.Add(new BlogLineChart { Month = "09", Count = sep });
            list.Add(new BlogLineChart { Month = "10", Count = oct });
            list.Add(new BlogLineChart { Month = "11", Count = nov });
            list.Add(new BlogLineChart { Month = "12", Count = dec });
            
            return list;
        }

        public JsonResult GetLineData()
        {
            var months = monthLine();
            var chartData = new object[months.Count + 1];
            chartData[0] = new object[]
            {

TutorGet/Controllers/TutorsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Security.Application;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutorGet.Models;
using TutorGet.Utils;

namespace TutorGet.Controllers
{
    public class TutorsController : Controller
    {
        private aspnetTutorGetEntities db = new aspnetTutorGetEntities();

        // GET: Tutors
        [Authorize]
        public ActionResult Search ()
        {
            //var tutors = db.Tutors.Include(t => t.Language);
           
            return View();
        }


        public ActionResult Index([DefaultValue(0)] int languageId, string language)
        {
            if (languageId == 0 && language == null)
            {
                var tutors = db.Tutors.Include(t => t.Language);
                return View(tutors.ToList());
            }
            else
            {
                var tutors = db.Tutors.Where(t => t.Language.Id == languageId && t.Language.LanguageName == language);
                return View(tutors.ToList());
            }
           
        }

        // GET: Tutors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutors.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            return View(tutor);
        }

        // GET: Tutors/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.LanguageId = new SelectList(db.Languages, "Id", "LanguageName");
            return View();
        }

        // POST: Tutors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Experience,HourlyPrice,Rate,Email,LanguageId")] Tutor tutor)
        {
            if (ModelState.IsValid)
            {
                db.Tutors.Add(tutor);
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }

            ViewBag.LanguageId = new SelectList(db.Languages, "Id", "LanguageName", tutor.LanguageId);
            return View(tutor);
        }

        // GET: Tutors/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutors.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            ViewBag.LanguageId = new SelectList(db.Languages, "Id", "LanguageName", tutor.LanguageId);
            return View(tutor);
        }

        // POST: Tutors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Experience,HourlyPrice,Rate,Email,LanguageId")] Tutor tutor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tutor).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }
            ViewBag.LanguageId = new SelectList(db.Languages, "Id", "LanguageName", tutor.LanguageId);
            return View(tutor);
        }

        // GET: Tutors/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutor tutor = db.Tutors.Find(id);
            if (tutor == null)
            {
                return HttpNotFound();
            }
            return View(tutor);
        }

        // POST: Tutors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tutor tutor = db.Tutors.Find(id);
            db.Tutors.Remove(tutor);
            db.SaveChanges();
            ViewBag.TheResult = true;
            //return RedirectToAction("Index");
            return View(tutor);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Send_Email(int id)
        {
            ViewBag.ToEmail = new SelectList(db.Tutors, "Id", "Email", id);
            var userId = User.Identity.GetUserId();
            var user = db.AspNetUsers.Find(userId);
            return View(new SendEmailViewModel());
        }

        [HttpPost]
        public ActionResult Send_Email(SendEmailViewModel model, int id)
        {
            //ViewBag.ToEmail = new SelectList(db.Tutors, "Id", "Email", id);
            var tutor = db.Tutors.Find(id);
            var tutoremail = tutor.Email;
            var userId = User.Identity.GetUserId();
            var user = db.AspNetUsers.Find(userId);
            var userEmail = user.Email;
            if (ModelState.IsValid)
            {
                try
                {
                    String toEmail = tutoremail;
                    String subject = "Message from user: " + userEmail;
                    String contents = Sanitizer.GetSafeHtmlFragment(model.Contents);

                    SendEmail se = new SendEmail();
                    se.Send(toEmail, subject, contents);

                    ViewBag.Result = "Email has been sent successfully.";

                    ModelState.Clear();

                    return View();
                }
                catch
                {
                    return View();
                }
            }

            return View();
        }


    }
}

TutorGet/Views/Bookings/Create.cshtml
@model TutorGet.Models.Booking


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Book a Lesson</h2>

@if (ViewBag.TheResult == true)
{
    <div id="myAlert" class="alert alert-success">
        The Lesson has been booked successfully!
    </div>
}

@if (ViewBag.TheResult == false)
{
    <div id="myAlert" class="alert alert-danger">
        Time clashes with another booked lesson!
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (ViewBag.TheResult == null || ViewBag.TheResult == false)
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)

            <div class="form-group">
                @Html.LabelFor(model => model.TutorId, "Tutor", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TutorId", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.TutorId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BookingTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BookingTime, new { htmlAttributes = new { @class = "form-control datetimepicker", @type = "datetime" } })
                    @Html.ValidationMessageFor(model => model.BookingTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Confirm" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to Tutor List", "Index", "Tutors")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').datetimepicker({
                format: "DD/MM/YY HH:mm",
                showTodayButton: true,
                widgetPositioning: {
                    horizontal: 'left',
                    vertical: 'bottom'
                }
            });
        });
    </script>
    <script>
        $(function () {
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD/MM/YY HH:mm", true).isValid();
            }
        });
    </script>
}

TutorGet/Views/Bookings/Delete.cshtml
@model TutorGet.Models.Booking

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cancel Booking</h2>

<h4>Are you sure you want to cancel this lesson?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tutor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tutor.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-default" /> |
            @Html.ActionLink("Back to Booking Calendar", "Index")
        </div>
    }
</div>

TutorGet/Views/Bookings/Details.cshtml
@model TutorGet.Models.Booking

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tutor.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tutor.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TutorGet/Views/Bookings/Edit.cshtml
@model TutorGet.Models.Booking

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reschedule Lesson</h2>

@if (ViewBag.TheResult == true)
{
    <div id="myAlert" class="alert alert-success">
        The Lesson has been rescheduled successfully!
    </div>
}

@if (ViewBag.TheResult == false)
{
    <div id="myAlert" class="alert alert-danger">
        Time clashes with another booked lesson!
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (ViewBag.TheResult == null || ViewBag.TheResult == false)
    {
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.TutorId)

            <div class="form-group">
                @Html.LabelFor(model => model.BookingTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BookingTime, new { htmlAttributes = new { @class = "form-control datetimepicker", @type = "datetime" } })
                    @Html.ValidationMessageFor(model => model.BookingTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to Booking Calendar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('.datetimepicker').datetimepicker({
                format: "DD/MM/YY HH:mm",
                showTodayButton: true,
                widgetPositioning: {
                    horizontal: 'left',
                    vertical: 'bottom'
                }
            });
        });
    </script>
    <script>
        $(function () {
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD/MM/YY HH:mm", true).isValid();
            }
        });
    </script>
}

TutorGet/Views/Bookings/Index.cshtml
@model IEnumerable<TutorGet.Models.Booking>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<script type="text/javascript" src="~/Scripts/rate/jquery.js"></script>
<script type="text/javascript" src="~/Scripts/rate/jRating.jquery.js"></script>
<link href="~/Content/jRating.jquery.css" rel="stylesheet" />*@


<h2 style="text-align: center">@Html.ActionLink("Check My Booking Report", "Report", "Bookings")</h2>
@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body" style="padding-right:25px">
                <p id="pDetails"></p>
                <div class="rate">
                <div style="text-align:right">
                    <span id="edit" class="glyphicon glyphicon-edit" aria-label="Edit"></span> |
                    <span id="rating" class="glyphicon glyphicon-thumbs-up" aria-label="Rate"></span> |
                    <span id="delete" class="glyphicon glyphicon-trash" aria-label="Delete"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</div>
<div id="calendar"></div>
<div style="display: none">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tutor.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookingTime)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr class="events">
                <td class="bookingid">
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td class="title">
                    @Html.DisplayFor(modelItem => item.Tutor.Name)
                </td>
                <td class="start">
                    @Html.DisplayFor(modelItem => item.BookingTime)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    @Html.ActionLink("Rate", "Rate", new { id = item.Id })

                </td>
            </tr>
        }
    </table>
</div>
@*
<script type="text/javascript">
    $(".rate").jRating({
        step: true,
        length: 5
    });

</script>*@

@section Scripts {

    @Scripts.Render("~/bundles/fullcalendar")
}

TutorGet/Views/Bookings/Rate.cshtml
@{
    ViewBag.Title = "Rate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Rate This Lesson </h3>

@using (Html.BeginForm())
{
    if (ViewBag.Result != null)
    {
        <div id="myAlert" class="alert alert-success">@ViewBag.Result</div>
    }
    else
    {
        <div class="k-content">
            <input id="rating" name="rating" style="width: 100%;" />
        </div>
        @*<div class="box" style="display:none">
                <div>
                    Old value: <label id=lblOldValue />
                </div>
                <div>
                    New Value: <label id=lblNewValue />
                </div>
            </div>*@
        <div style="padding-left:10px; margin-top:10px;">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    }
    <div>
        @Html.ActionLink("Back to Booking Calendar", "Index")
    </div>
}


<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.3.1023/styles/kendo.default-v2.min.css" />
<script src="https://kendo.cdn.telerik.com/2019.3.1023/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2019.3.1023/js/kendo.all.min.js"></script>
<script>
    (function ($) {
        $(document).ready(function () {
            $("#rating").kendoRating({
                min: 1,
                max: 5,
                value:@Html.Raw(Json.Encode(ViewBag.Value))
                //change: onChange,
            });

            @*function onChange(e) {
                $("#lblOldValue").text(e.oldValue)
                $("#lblNewValue").text(e.newValue)
            }*@
        });
    })(jQuery);
</script>

<style>
    .k-rating-item.k-state-selected {
        color: #f4c239
    }

    .k-rating-item.k-state-hover {
        color: #f4c239
    }

    .k-content {
        color: black
    }
</style>