TutorGet/Models/UserEvent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorGet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserEvent
    {
        public int Id { get; set; }
        [Display(Name = "User")]
        public string UserId { get; set; }
        [Display(Name = "Event")]
        public int EventId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Event Event { get; set; }
    }
}

TutorGet/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutorGet.Models;

namespace TutorGet.Controllers
{
    public class EventsController : Controller
    {
        private aspnetTutorGetEntities db = new aspnetTutorGetEntities();

        // GET: Events
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EventName,Description,Time,Address,Latitude,Longitude")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EventName,Description,Time,Address,Latitude,Longitude")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            ViewBag.TheResult = true;
            //return RedirectToAction("Index");
            return View(@event);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TutorGet/Controllers/UserEventsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TutorGet.Models;

namespace TutorGet.Controllers
{
    public class UserEventsController : Controller
    {
        private aspnetTutorGetEntities db = new aspnetTutorGetEntities();

        // GET: UserEvents
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var userEvents = db.UserEvents.Where(s => s.UserId == userId).ToList();

            return View(userEvents);
        }

        // GET: UserEvents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            return View(userEvent);
        }

        // GET: UserEvents/Create
        [Authorize]
        public ActionResult Create(int eventid)
        {
            //ViewBag.EventId = new SelectList(db.Events, "Id", "EventName", eventid);
            ViewBag.Event = from eve in db.Events
                             where eve.Id == eventid
                             select eve;
            return View();
        }

        // POST: UserEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,UserId,EventId")] UserEvent userEvent)
        {
            userEvent.UserId = User.Identity.GetUserId();
            ModelState.Clear();
            TryValidateModel(userEvent);

            if (db.UserEvents.Any(e => e.EventId == userEvent.EventId && e.UserId == userEvent.UserId))
            {
                ViewBag.TheResult = false;
            }

            else if (ModelState.IsValid)
            {
                db.UserEvents.Add(userEvent);
                db.SaveChanges();
                ViewBag.TheResult = true;
                //return RedirectToAction("Index");
            }

            return View(userEvent);
        }

        // GET: UserEvents/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            return View(userEvent);
        }

        // POST: UserEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,EventId")] UserEvent userEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userEvent);
        }

        // GET: UserEvents/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserEvent userEvent = db.UserEvents.Find(id);
            if (userEvent == null)
            {
                return HttpNotFound();
            }
            return View(userEvent);
        }

        // POST: UserEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserEvent userEvent = db.UserEvents.Find(id);
            db.UserEvents.Remove(userEvent);
            db.SaveChanges();
            ViewBag.TheResult = true;
            //return RedirectToAction("Index");
            return View(userEvent);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TutorGet/Views/UserEvents/Create.cshtml
@model TutorGet.Models.UserEvent

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bookmark Event</h2>
@if (ViewBag.TheResult == true)
{
    <div id="myAlert" class="alert alert-success">
        This event has been bookmarked successfully!
    </div>
}

@if (ViewBag.TheResult == false)
{
    <div id="myAlert" class="alert alert-danger">
        This event has already been bookmarked!
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (ViewBag.TheResult == null)
    {

        <div class="form-horizontal">
            <h4>Do you want to bookmark this event?</h4>
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)
            @Html.HiddenFor(model => model.EventId)
            
           @* <div class="form-group" >
                    @Html.LabelFor(model => model.EventId, "Event", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Event", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly"})
                        @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
                    </div>
                </div>*@

        <div class="form-group">
            @*<div class="col-md-offset-2 col-md-10">*@
            <div class="col-md-12">
                <input type="submit" value="Confirm" class="btn btn-default" />
            </div>
        </div>
        </div>
    }
}

    <div>
        @Html.ActionLink("Back to Event List", "Index", "Events")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

TutorGet/Views/UserEvents/Delete.cshtml
@model TutorGet.Models.UserEvent

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Remove From Event Bookmark </h2>
@if (ViewBag.TheResult == true)
{
    <div id="myAlert" class="alert alert-success">
        This event has been removed successfully!
    </div>
    <div>
        @Html.ActionLink("Back to My Bookmark", "Index")
    </div>

}

@if (ViewBag.TheResult == null)
{
    <h4>Are you sure you want to remove this event?</h4>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Event.EventName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Event.EventName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Event.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Event.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Event.Time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Event.Time)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to My Bookmark", "Index")
            </div>
        }
    </div>
}

TutorGet/Views/UserEvents/Details.cshtml
@model TutorGet.Models.UserEvent

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TutorGet/Views/UserEvents/Edit.cshtml
@model TutorGet.Models.UserEvent

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserEvent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TutorGet/Views/UserEvents/Index.cshtml
@model IEnumerable<TutorGet.Models.UserEvent>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Event Bookmark</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Event.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Event.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Event.Time)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Event.EventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Event.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Event.Time)
        </td>
        <td>
            <a href="@Url.Action("Delete", "UserEvents", new { id = item.Id })" class="glyphicon glyphicon-trash" aria-label="Delete">
            </a>
    </td>
</tr>
}

</table>